version: "3.8"

services: 
  mysql:
    container_name: mysql
    image: mysql:8.0
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=yourStrongPassword12#
      - MYSQL_DATABASE=taskboarddb
      - MYSQL_USER=taskboarduser
      - MYSQL_PASSWORD=yourStrongPassword12#
    volumes: 
      - mysqldata:/var/lib/mysql

  web-app:
    container_name: web-app
    build:
      dockerfile: ./TaskBoard.WebApp/Dockerfile
    ports: 
      - "5000:8080"
    restart: on-failure
    depends_on:
      - mysql

volumes:
  mysqldata: